name: Check terlar

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'profiles/terlar/**'
      - 'flake.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#terlar --dry-run --show-trace
