name: Check terlar

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'profiles/terlar/**'
      - 'flake.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: nix build .#terlar --dry-run
