name: Check scimax

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'profiles/scimax/**'
      - 'flake.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - run: nix build .#scimax --dry-run
