name: Update flake inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 6'

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.pr.outputs.pull-request-operation == 'created' || steps.pr.outputs.pull-request-operation == 'updated' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17

    - name: Update Nix libraries
      run: |
        nix flake lock \
        --update-input twist \
        --update-input flake-utils \
        --update-input org-babel

    - name: Update dependencies (terlar)
      run: |
        nix run .#update-terlar --impure
        nix run .#lock-terlar --impure

    - name: Update dependencies (scimax)
      run: |
        nix run .#update-scimax --impure
        nix run .#lock-scimax --impure

    - uses: peter-evans/create-pull-request@v4
      id: pr
      with:
        commit-message: 'Update flake inputs'
        base: master
        title: 'chore: Update dependencies'
        branch: create-pull-request/update
        labels: automation,update

  check-terlar:
    needs: ['update']
    if: ${{ needs.update.outputs.updated == 'true' }}
    uses: emacs-twist/examples/.github/workflows/check-terlar.yml@create-pull-request/update

  check-scimax:
    needs: ['update']
    if: ${{ needs.update.outputs.updated == 'true' }}
    uses: emacs-twist/examples/.github/workflows/check-scimax.yml@create-pull-request/update
