name: Update ELPA packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update dependencies (terlar)
      run: |
        nix run .#lock-terlar --impure
        nix run .#update-terlar --impure --show-trace

    - name: Update dependencies (scimax)
      run: |
        nix run .#lock-scimax --impure
        nix run .#update-scimax --impure --show-trace

    - run: git push origin ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
