name: 'Update all inputs in the flake.lock'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 3 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update flake inputs
      run: nix flake update --show-trace

    - uses: peter-evans/create-pull-request@v5
      with:
        commit-message: 'Update flake inputs'
        token: ${{ secrets.PAT_FOR_PR }}
        base: master
        title: 'chore: Update dependencies'
        branch: create-pull-request/update-all
        labels: automation,update
